### PR TITLE
Use threading to record audio in parallel to transcribing/translating…

### LINKED ISSUE #10: Audio is lost
Hello friend! Thank you for your great initiative with this repository, it's very useful!
However, I noticed that because the call to the model is a blocking call, the voice input during the time the AI model is working is lost.
In a private repo I fixed this with threading and queues, would you be interested in a Pull Request for this repo as well?

### PR DESCRIPTION
**Pull request by tatellos**
… it. Previously, during the blocking synchronous call to the model, the microphone input was missed.

Fixes #10

### CODE REVIEW

**Comment by tatellos** [comment]
@mallorbc Is there anything that I should clarify more, or anything else that is blocking you from merging this PR? :)

**Comment by mallorbc** [comment]
> @mallorbc Is there anything that I should clarify more, or anything else that is blocking you from merging this PR? :)

No sorry. Just been busy and need to test before merging. Thanks for the PR

**Comment by mallorbc** [comment]
Finally got around to this.  Works great!

**Comment by mallorbc** [comment]
Thanks!

**Pull request merged**
