### PR TITLE
a small fix to transcribe audio faster

### PR DESCRIPTION
**Pull request by iamitaliya**
Saving the audio and then transcribing seems to be a bit slower. Whisper itself is faster but the saving process itself seems to take around 10 seconds for me. Added a small fix to transcribe the audio directly without storing it as a .wav file.

### CODE REVIEW

**Comment by mallorbc** [comment]
I will test this, but assuming it works as you say this is a great change!

What is the value 32768.0 in the divisor?

**Comment by bottledmind** [comment]
This might fail due to different preprocessing method. 
If it does not reduce the quality significantly, consider trying to contribute to original repo.

**Comment by bottledmind** [comment]
@mallorbc 
https://github.com/openai/whisper/blob/7f3e408e092e73d472036ae2e3fba1e7c68ca4e6/whisper/audio.py#L49

**Comment by iamitaliya** [comment]
> @mallorbc https://github.com/openai/whisper/blob/7f3e408e092e73d472036ae2e3fba1e7c68ca4e6/whisper/audio.py#L49

So this is how the audio is processed when reading from an audio file. As the audio file is temporarily saved just to be read by this method again. We could cut the middle process. 
I have not tested the quality to be specific but I don't think it should be much affected as it is converting raw audio data directly to the torch sensor.
@bottledmind Could you please explain how it would fail due to different preprocessing methods?

**Comment by bottledmind** [comment]
@iamitaliya Nah, this part of preprocessing is gonna work the same way. I'm pretty sure about that

> @mallorbc https://github.com/openai/whisper/blob/7f3e408e092e73d472036ae2e3fba1e7c68ca4e6/whisper/audio.py#L49

But I'm not that sure about lines 41-45
https://github.com/openai/whisper/blob/7f3e408e092e73d472036ae2e3fba1e7c68ca4e6/whisper/audio.py#L41
I'm not an audio guy, but I've witnessed differences in the model outputs for .jpg and .png versions of the same image. So, I worry about the ffmpeg codec parameter

**Comment by mallorbc** [comment]
While I still need to test this method for this repo.  I have tested it in a similar application and it seems to work well.  I think it will work and is a great addition.  After testing in the repo later today I will merge.

**Comment by shervinemami** [comment]
Hi @mallorbc , I think this change looks like a good idea to me 👌 But can I ask that you provide an option to continue using the old (wav file) method? I assume this new faster method is good as the default, but it would be good to be able to pass an argument so it stores & loads the wav file, so that some people specifically wanting the wav file functionality can easily use that.

**Comment by mallorbc** [comment]
Sorry, been busy.  I am doing this as I type now.  Will merge within a few hours.

**Comment by mallorbc** [comment]
Confirmed working on my m1 mac.  Merging and will provide legacy support soon after.

**Comment by mallorbc** [comment]
@shervinemami Added legacy support.  Controlled now with a flag.

**Pull request merged**
